import { logo } from './assets';

export const skills = {
    primary: [
        {
            key: 'reactjs',
            logo: logo.reactjs,
            title: 'ReactJS',
            size: '4rem',
        },
        {
            key: 'expressjs',
            logo: logo.expressjs,
            title: 'ExpressJS',
            size: '4rem',
        },
        {
            key: 'typescript',
            logo: logo.typescript,
            title: 'TypeScript',
            size: '3.5rem',
            isRound: true,
        },
        {
            key: 'nodejs',
            logo: logo.nodejs,
            title: 'NodeJS',
            size: '2.5rem',
            width: '4rem',
        },
        {
            key: 'docker',
            logo: logo.docker,
            title: 'Docker',
            size: '4.5rem',
        },
    ],
    frontend: [
        {
            key: 'reactjs',
            logo: logo.reactjs,
            title: 'ReactJS',
            size: '4rem',
        },
        {
            key: 'styledcomponents',
            logo: logo.styledcomponents,
            title: 'Styled Components',
            size: '4.0rem',
            fontSize: 'small',
        },
        {
            key: 'typescript',
            logo: logo.typescript,
            title: 'TypeScript',
            size: '3.5rem',
            isRound: true,
        },
        {
            key: 'css',
            logo: logo.css,
            title: 'CSS3',
            size: '4.5rem',
        },
        {
            key: 'redux',
            logo: logo.redux,
            title: 'Redux',
            size: '4rem',
        },
        {
            key: 'javascript',
            logo: logo.js,
            title: 'JavaScript',
            size: '3.5rem',
            isRound: true,
        },
        {
            key: 'html',
            logo: logo.html,
            title: 'HTML5',
            size: '4.5rem',
        },
        {
            key: 'saga',
            logo: logo.saga,
            title: 'Redux Saga',
            size: '2.2rem',
            width: '3.6rem',
        },
        {
            key: 'apollo',
            title: 'Apollo GraphQL',
            logo: logo.apollo,
        },
        {
            key: 'gatsbyjs',
            logo: logo.gatsbyjs,
            title: 'GatsbyJS',
            size: '3.5rem',
        },
    ],
    devops: [
        {
            key: 'docker',
            logo: logo.docker,
            title: 'Docker',
            size: '4.5rem',
        },
        {
            key: 'terraform',
            logo: logo.terraform,
            title: 'Terraform',
            size: '1.15rem',
            width: '4.8rem',
        },
        {
            key: 'aws',
            logo: logo.aws,
            title: 'AWS',
            size: '4.5rem',
        },
        {
            key: 'kubernetes',
            logo: logo.kubernetes,
            title: 'Kubernetes',
            size: '3.5rem',
        },
        {
            key: 'serverless',
            logo: logo.serverless,
            title: 'Serverless',
            size: '3.5rem',
            isRound: true,
        },
        {
            key: 'vagrant',
            logo: logo.vagrant,
            title: 'Vagrant',
            size: '1.15rem',
            width: '4.2rem',
        },
    ],
    dated: [
        {
            key: '1cbitrix',
            logo: logo.bitrix,
            title: '1C Bitrix',
            size: '3.5rem',
        },
        {
            key: 'meteorjs',
            logo: logo.meteorjs,
            title: 'MeteorJS',
            size: '4rem',
        },
        {
            key: 'php',
            logo: logo.php,
            title: 'PHP',
            size: '3.5rem',
            isRound: true,
        },
        {
            key: 'sass',
            logo: logo.sass,
            title: 'SASS',
            size: '2.5rem',
            width: '4rem',
        },
        {
            key: 'less',
            logo: logo.less,
            title: 'LESS',
            size: '2.0rem',
            width: '4.5rem',
        },
    ],
    util: [
        {
            key: 'git',
            logo: logo.git,
            title: 'GIT',
            size: '4rem',
        },
        {
            key: 'hg',
            logo: logo.hg,
            title: 'Mercurial',
            size: '3rem',
            width: '3.1rem',
        },
    ],
    backend: [
        {
            key: 'nodejs',
            logo: logo.nodejs,
            title: 'NodeJS',
            size: '2.5rem',
            width: '4rem',
        },
        {
            key: 'expressjs',
            logo: logo.expressjs,
            title: 'ExpressJS',
            size: '4rem',
        },
        {
            key: 'nestjs',
            logo: logo.nestjs,
            title: 'NestJS',
            size: '3.5rem',
        },
        {
            key: 'mongodb',
            logo: logo.mongodb,
            title: 'MongoDB',
            size: '4.5rem',
        },
        {
            key: 'mysql',
            logo: logo.mysql,
            title: 'MySQL',
            size: '4.5rem',
            isRound: true,
        },
        {
            key: 'postgressql',
            logo: logo.postgressql,
            title: 'PostgresSQL',
            size: '4.0rem',
        },
        {
            key: 'redis',
            logo: logo.redis,
            title: 'Redis',
            size: '4rem',
        },
        {
            key: 'typeorm',
            logo: logo.typeorm,
            title: 'TypeORM',
            size: '2rem',
            width: '4rem',
        },
        {
            key: 'linux',
            logo: logo.linux,
            title: 'Linux',
            size: '4rem',
            offsetX: '0.7rem',
        },
    ],
    familiar: [
        {
            key: 'angular',
            logo: logo.angularjs,
            title: 'AngularJS',
            size: '4rem',
        },
        {
            key: 'perl',
            logo: logo.perl,
            title: 'Perl',
            size: '2rem',
            width: '3rem',
        },
        {
            key: 'sharp',
            logo: logo.csharp,
            title: 'C#',
            size: '2.5rem',
            width: '3rem',
        },
        {
            key: 'python',
            logo: logo.python,
            title: 'Python',
            size: '1.2rem',
            width: '4rem',
        },
    ],
};
