import { logo } from './assets';

const skillList = [
    {
        key: 'reactjs',
        logo: logo.reactjs,
        title: 'React',
        size: '4rem',
    },
    {
        key: 'typescript',
        logo: logo.typescript,
        title: 'TypeScript',
        size: '3.5rem',
        isRound: true,
    },
    {
        key: 'css',
        logo: logo.css,
        title: 'CSS3',
        size: '4.5rem',
    },
    {
        key: 'javascript',
        logo: logo.js,
        title: 'JavaScript',
        size: '3.5rem',
        isRound: true,
    },
    {
        key: 'html',
        logo: logo.html,
        title: 'HTML5',
        size: '4.5rem',
    },
    {
        key: 'apollo',
        title: 'Apollo GraphQL',
        logo: logo.apollo,
    },
    {
        key: 'gatsbyjs',
        logo: logo.gatsbyjs,
        title: 'Gatsby',
        size: '3.5rem',
    },
    {
        key: 'mobx',
        logo: logo.mobx,
        title: 'MobX',
        size: '3.5rem',
    },
    {
        key: 'reactquery',
        logo: logo.reactquery,
        title: 'React query',
        size: '3.5rem',
        //width: '3rem',
    },
    {
        key: 'styledcomponents',
        logo: logo.styledcomponents,
        title: 'Styled Components',
        size: '4.0rem',
        fontSize: 'small',
    },
    {
        key: 'git',
        logo: logo.git,
        title: 'GIT',
        size: '4rem',
    },
    {
        key: 'vercel',
        logo: logo.vercel,
        title: 'Vercel',
        size: '2.5rem',
        width: '3.0rem',
    },
    {
        key: 'nodejs',
        logo: logo.nodejs,
        title: 'Node',
        size: '2.5rem',
        width: '4rem',
    },
    {
        key: 'docker',
        logo: logo.docker,
        title: 'Docker',
        size: '4.5rem',
    },
    {
        key: 'terraform',
        logo: logo.terraform,
        title: 'Terraform',
        size: '1.15rem',
        width: '4.8rem',
    },
    {
        key: 'kubernetes',
        logo: logo.kubernetes,
        title: 'Kubernetes',
        size: '3.5rem',
    },
    {
        key: 'serverless',
        logo: logo.serverless,
        title: 'Serverless',
        size: '3.5rem',
        isRound: true,
    },
    {
        key: 'aws',
        logo: logo.aws,
        title: 'AWS',
        size: '4.5rem',
    },
    {
        key: 'expressjs',
        logo: logo.expressjs,
        title: 'Express',
        size: '4rem',
    },
    {
        key: 'nestjs',
        logo: logo.nestjs,
        title: 'Nest',
        size: '3.5rem',
    },
    {
        key: 'mongodb',
        logo: logo.mongodb,
        title: 'MongoDB',
        size: '4.5rem',
    },
    {
        key: 'mysql',
        logo: logo.mysql,
        title: 'MySQL',
        size: '4.5rem',
        isRound: true,
    },
    {
        key: 'postgressql',
        logo: logo.postgressql,
        title: 'PostgreSQL',
        size: '4.0rem',
    },
    {
        key: 'redis',
        logo: logo.redis,
        title: 'Redis',
        size: '4rem',
    },
    {
        key: 'typeorm',
        logo: logo.typeorm,
        title: 'TypeORM',
        size: '2rem',
        width: '4rem',
    },
    {
        key: 'linux',
        logo: logo.linux,
        title: 'Linux',
        size: '4rem',
        offsetX: '0.7rem',
    },
    {
        key: 'sass',
        logo: logo.sass,
        title: 'SASS',
        size: '2.5rem',
        width: '4rem',
    },
    {
        key: 'less',
        logo: logo.less,
        title: 'LESS',
        size: '2.0rem',
        width: '4.5rem',
    },
    {
        key: 'redux',
        logo: logo.redux,
        title: 'Redux',
        size: '4rem',
    },
    {
        key: 'saga',
        logo: logo.saga,
        title: 'Redux Saga',
        size: '2.2rem',
        width: '3.6rem',
    },
    {
        key: 'vagrant',
        logo: logo.vagrant,
        title: 'Vagrant',
        size: '1.15rem',
        width: '4.4rem',
    },
    {
        key: 'auth0',
        logo: logo.auth0,
        title: 'Auth0',
        size: '3rem',
        width: '2.7rem',
    },
    {
        key: 'netlify',
        logo: logo.netlify,
        title: 'Netlify',
        size: '3.5rem',
        width: '3.5rem',
    },
    {
        key: 'meteorjs',
        logo: logo.meteorjs,
        title: 'Meteor',
        size: '4rem',
    },
    {
        key: 'php',
        logo: logo.php,
        title: 'PHP',
        size: '3.5rem',
        isRound: true,
    },
    {
        key: 'angular',
        logo: logo.angularjs,
        title: 'Angular',
        size: '4rem',
    },
    {
        key: 'perl',
        logo: logo.perl,
        title: 'Perl',
        size: '2rem',
        width: '3rem',
    },
    {
        key: 'sharp',
        logo: logo.csharp,
        title: 'C#',
        size: '2.5rem',
        width: '3rem',
    },
    {
        key: 'python',
        logo: logo.python,
        title: 'Python',
        size: '1.2rem',
        width: '4rem',
    },
    {
        key: 'kotlin',
        logo: logo.kotlin,
        title: 'Kotlin',
        size: '2.5rem',
        //width: '3rem',
    },
    {
        key: '1cbitrix',
        logo: logo.bitrix,
        title: '1C Bitrix',
        size: '3.5rem',
    },
    {
        key: 'hg',
        logo: logo.hg,
        title: 'Mercurial',
        size: '3rem',
        width: '3.1rem',
    },
    {
        key: '3dsmax',
        logo: logo.autodesk,
        title: '3DS Max',
        size: '3rem',
        width: '3.1rem',
    },
    {
        key: 'vray',
        logo: logo.vray,
        title: 'VRay',
        size: '5rem',
    },
    {
        key: 'jamstack',
        logo: logo.jamstack,
        title: 'Jamstack',
        size: '3rem',
    },
];

export const skills: Record<
    string,
    typeof skillList extends (infer U)[] ? U : unknown
> = {};

skillList.forEach(skill => (skills[skill.key] = skill));
